// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppayqcrkfjwwgtjrlulv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwYXlxY3JrZmp3d2d0anJsdWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjI2ODksImV4cCI6MjA3MjM5ODY4OX0.wxuQrPvItlH3b5i-0diNo7BjDZ-pTWVAuM45Gt7U8jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});